# port config
server:
  port: 8001
  
# datasource config
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: C##MINGLE
    password: MINGLE
  mail:
    host: smtp.naver.com
    port: 465
    username: qwe030223@naver.com
    password: weqaz100400
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true 
    
# jpa config
  jpa:
    generate-ddl: false
    show-sql: true
    database: oracle
    properties:
      hibernate:
        '[format_sql]' : true
  # SSE 통신 사용 시, DB connection을 닫기 위한 설정
    open-in-view: false
    
# maximum upload size
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    time-zone: Asia/Seoul

# 이미지 저장할 위치와 응답 시 이미지 주소 설정
image:
  # WebConfig에 세팅
  add-resource-locations: file:////profileImgs/
  add-resource-handler: /profileImgs/**
  # ProductService에 세팅
  image-dir: /profileImgs # 이미지들을 저장할 상대 경로 설정
  image-url: http://localhost:8001/profileImgs/ # 찾고자 하는 이미지들의 경로
#  image-url: http://**아이피주소또는도메인**:8001/profileImgs/
  
# HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
# Secret 값은 특정 문자열을 Base64 로 인코딩한 값 사용
jwt:
  secret: asdfjp298pafo1320efqw0udvnh0er0h412r08byfdq9dsvh02143908hfeqwn80fdqs0nfdqs0n412013rq0nqefn08dfas0das730732g86923

dynamic:
  password: my_actual_password  